- .github/workflows/publishBetaOnly.yml
- .github/workflows/testCommitExceptMain.yml
> chore: pr for GHA W-17705444

- .github/workflows/createReleasePR.yml
- .github/workflows/generateReleaseChangelog.yml
- .github/workflows/initiateNewRelease.yml
- .github/workflows/publishBetaOnly.yml
> chore: more GHAs W-17705444

- .github/workflows/afdxE2E.yml
- .github/workflows/runE2ETest.yml
- .github/workflows/updatePublicRepo.yml
> fix: testing releaseCI W-17705444

- package-lock.json
- package.json
- src/extension.ts
- src/types/TestNodes.ts
- src/views/testOutlineProvider.ts
- src/views/testRunner.ts
updates `agents` library with new mocks/types
@W-17775110@
> fix: update Agents lib, fix colors in scenarios W-17775110

- package-lock.json
- package.json
- src/extension.ts
- src/types/TestNodes.ts
- src/views/testOutlineProvider.ts
- src/views/testRunner.ts
changes in-progress test output
adds detailed test view
```
┌──────────────────────────────────────────┐
Local_Info_Agent_Test (Test Case: 1)  
└──────────────────────────────────────────┘
"Tell me about local events happenning tonight."
┌────────── Topic ─ FAILURE ────────┐
EXPECTED: Local_Events_Information_INVALID
ACTUAL: Local_Events_Information
STATS: topic_sequence_match, 0
└───────────────────────────────────┘
┌────────── Action ─ PASS ──────────┐
EXPECTED: []
ACTUAL: []
STATS: action_sequence_match, 1
└───────────────────────────────────┘
```
@W-17767574@
> Wr/detailed output W-17767574

- package-lock.json
- package.json
- src/views/testOutlineProvider.ts
fixes how API names are parsed
#<Insert GitHub Issue>, @W-17767574@
> W-17767574 fix: update where API name is parsed from

- .github/workflows/build.yml
- .vscodeignore
- esbuild.config.js
- package-lock.json
- package.json
- scripts/vsce-bundled-extension.ts
- src/commands/openAgentInOrg.ts
- src/extension.ts
- src/services/coreExtensionService.ts
- src/types/TestNodes.ts
- src/views/testRunner.ts
- tsconfig.json
- Use bundled libraries instead (agents-bundle, core-bundle)
- Modify build workflow to run npm run bundle:extension
- Decrease startup time from ~3450 ms to ~170 ms
@W-17767554@
> feat(W-17767554): bundling

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- CONTRIBUTING/developing.md
- README.md
adds missing docs
updates readme
@W-17847937@
> docs: add contributing/code_of_conduct/readme update W-17847937

- README.md
> W-17856150: first pass at the VS Code extension readme

- jest.config.js
- scripts/setup-jest.ts
- src/extension.ts
- src/views/testOutlineProvider.ts
- test/commands/openAgentInOrg.test.ts
- test/services/coreExtensionService.test.ts
- test/views/testOutlineProvider.test.ts
- Creates jest tests for some files
@W-17853592@
> test(W-17853592): add some unit tests

- .github/workflows/build.yml
- src/views/testOutlineProvider.ts
> chore(W-17847945): add pre-release tag to build

- src/commands/openAgentInOrg.ts
- src/extension.ts
- src/services/coreExtensionService.ts
- src/views/testRunner.ts
- test/commands/openAgentInOrg.test.ts
> fix: activates, saves test data W-17767574

- src/views/testRunner.ts
@W-17875034@
changes output to match UX suggestions
```bash
════════════════════════════════════════════════════════════════════════
CASE #1 - Willie_Test_3
════════════════════════════════════════════════════════════════════════
"Are there any good bike rides around the resort? Ideally enduro rides, ranging from 7-10 miles and less than 4000 feet of climbing"
❯ TOPIC: PASS ✅
────────────────────────────────────────────────────────────────────────
EXPECTED : Local_Events_Information
ACTUAL   : Local_Events_Information
SCORE    : 1
❯ ACTION: FAILURE ❌
────────────────────────────────────────────────────────────────────────
EXPECTED : ["EmployeeCopilot__AnswerQuestionsWithKnowledge"]
ACTUAL   : []
SCORE    : 0
❯ OUTCOME: FAILURE ❌
───────────────────────────────────────────────────────────── …
```
> fix: update output from UX W-17875034

- .github/workflows/build.yml
- .github/workflows/publishOpenVSX.yml
- .github/workflows/publishVSCode.yml
- .gitignore
- CHANGELOG.md
- package.json
- Final updates for publishing
@W-17910136@
> chore(W-17910136): updates for publishing

- CHANGELOG.md
Quick edit of the changelog
[skip-validate-pr]
> docs(W-17910136): Edit changelog

- package.json
- src/extension.ts
- src/views/testRunner.ts
#<Insert GitHub Issue>, @@
<insert gif and/or summary>
<insert gif and/or summary>
<insert helpful notes to help your QE get started>
> fix: remove view change, update error message W-17892720

- .github/workflows/publishOpenVSX.yml
- .github/workflows/publishVSCode.yml
- .github/workflows/slackNotification.yml
- Updates publish notifications
[skip-validate-pr]
> chore: update publish notifications

- README.md
- package-lock.json
- package.json
- src/views/testRunner.ts
updates output for new OOTB metrics
```bash
❯ METRICS (Value/Threshold)
────────────────────────────────────────────────────────────────────────
✅ : COMPLETENESS (0.8/0.6) 
✅ : COHERENCE (1/0.6) 
✅ : CONCISENESS (0.8/0.6) 
⏱️ : OUTPUT LATENCY (9154ms)  
────────────────────────────────────────────────────────────────────────
```
@W-18394826@
@W-18272822@
each metric output would get it's own section, using the wrong expected/actual values
metrics all grouped, and using correct value (score)
use Vivek's prod org, or 254.12+ maybe it's 254.13+
> PREVIEW + GA W-18272822

- package.json
Adds properties to accommodate O11y reporter initialisation
@W-18481790@
> fix: properties to accommodate O11y reporter initialisation - W-18481790

- README.md
Updates README to say the plugin is JIT, but you can isntall it manually if you want. 
@W-18742494@
> W-18742494: Update README.md

- package-lock.json
- package.json
- src/utils/jsonFormatter.ts
- src/views/testOutlineProvider.ts
- src/views/testRunner.ts
- tsconfig.json
adds a generated data. invoked actions section to the output
@W-19179085@
requires: https://github.com/forcedotcom/agents/pull/136
> fix: add generatedData.invokedActions to output, when present @W-19179085@
